### ISSUE TITLE
Submission quality

### ISSUE THREAD

**Issue by dwividha** [wealth42/nick-fury#37]
Might be useful to add this to Assessment criteria:
- No submissions to be made with compressed/binary files - all source code should be version controlled and visible in plain text in github.
- Follow [best practices](https://github.community/t/best-practices-for-pull-requests/10195) for pull requests
- Commits must adhere to [these guidelines](https://chris.beams.io/posts/git-commit/)

**Comment by pradnyalgandhi** [comment]
Issue has been solved.
